version: "0.1"
environments:
  - name: master
    branch: master
    mode: pull-request
apps:
  - name: isoratas.com
    path: ""
    text-resources:
      - path: "*.html"
        format: html-hardcoded
      - path: "*.md"
        format: html-hardcoded
